spring.application.name=uripet

spring.datasource.url=jdbc:postgresql://dpg-d8ol8hsm0tmc73ct01f0-a.oregon-postgres.render.com:5432/uripet_db?sslmode=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}

spring.security.jwt.secret=${JWT_SECRET}
spring.security.jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

springdoc.swagger-ui.path=/api/docs
spring.jpa.open-in-view=false

aws.region=${AWS_REGION}

server.port=${PORT:8080}